# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{muck-groups}
  s.version = "3.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin Ball", "Joel Duffin"]
  s.date = %q{2010-10-15}
  s.description = %q{Groups are an assembly of people}
  s.email = %q{justin@tatemae.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.homepage = %q{http://github.com/tatemae/muck-groups}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{muck-groups}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Groups for muck}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<sanitize>, [">= 0"])
      s.add_runtime_dependency(%q<aasm>, [">= 0"])
      s.add_runtime_dependency(%q<paperclip>, [">= 0"])
      s.add_runtime_dependency(%q<geokit>, [">= 0"])
      s.add_runtime_dependency(%q<friendly_id>, [">= 0"])
      s.add_runtime_dependency(%q<muck-engine>, [">= 0"])
      s.add_runtime_dependency(%q<muck-users>, [">= 0"])
      s.add_runtime_dependency(%q<muck-profiles>, [">= 0"])
      s.add_runtime_dependency(%q<muck-comments>, [">= 0"])
      s.add_runtime_dependency(%q<muck-solr>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<sanitize>, [">= 0"])
      s.add_dependency(%q<aasm>, [">= 0"])
      s.add_dependency(%q<paperclip>, [">= 0"])
      s.add_dependency(%q<geokit>, [">= 0"])
      s.add_dependency(%q<friendly_id>, [">= 0"])
      s.add_dependency(%q<muck-engine>, [">= 0"])
      s.add_dependency(%q<muck-users>, [">= 0"])
      s.add_dependency(%q<muck-profiles>, [">= 0"])
      s.add_dependency(%q<muck-comments>, [">= 0"])
      s.add_dependency(%q<muck-solr>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<sanitize>, [">= 0"])
    s.add_dependency(%q<aasm>, [">= 0"])
    s.add_dependency(%q<paperclip>, [">= 0"])
    s.add_dependency(%q<geokit>, [">= 0"])
    s.add_dependency(%q<friendly_id>, [">= 0"])
    s.add_dependency(%q<muck-engine>, [">= 0"])
    s.add_dependency(%q<muck-users>, [">= 0"])
    s.add_dependency(%q<muck-profiles>, [">= 0"])
    s.add_dependency(%q<muck-comments>, [">= 0"])
    s.add_dependency(%q<muck-solr>, [">= 0"])
  end
end

